### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by anthony-geoghegan** [iridakos/iridakos.github.io#5]
Hi Lazarus,

I just came across your beautiful site via https://news.ycombinator.com/item?id=20037366
I noticed that on each page I checked, the `href` for the links in *Recent Posts* and *Related Posts* is set to the URL of the current page instead of the intended URL. I couldn't find an email address on your About page so I figured creating an issue here would be the best way of letting you know.

Best wishes,
Anthony

**Comment by iridakos** [comment]
@anthony-geoghegan Thank you **very very** much for pointing it out and reporting it! I just fixed that. :+1: :+1: :+1:
